__default__:
  partition: Lewis,hpc5,General
  time: 0-02:00
  cpus: 1
  mem: 1G
RenameSamples:
  time: 0-04:00
  mem: 1G
  job-name: RenameSamples
  output: reports/RenameSamples-%j.slurm.out
PreformatRP:
  time: 0-01:00
  mem: 1G
  job-name: PreformatRP
  output: reports/PreformatRP-%j.slurm.out
PreformatNRP:
  time: 0-01:00
  mem: 1G
  job-name: PreformatNRP
  output: reports/PreformatNRP-%j.slurm.out
ImputeRP:
  time: 0-08:00
  mem: 120G
  cpus: 15
  job-name: ImputeRP
  output: reports/ImputeRP-%j.slurm.out
ImputeNRP:
  time: 0-04:00
  mem: 100G
  cpus: 15
  job-name: ImputeNRP
  output: reports/ImputeNRP-%j.slurm.out
MergeVCFs:
  time: 0-01:00
  mem: 2G
  job-name: MergeVCFs
  output: reports/MergeVCFs-%j.slurm.out
Subset:
  time: 0-01:00
  mem: 500M
  job-name: Subset
  output: reports/Subset-%j.slurm.out
SNPsOnly:
  time: 0-01:00
  mem: 500M
  job-name: SNPsOnly
  output: reports/SNPsOnly-%j.slurm.out
EstimateBlocks:
  time: 0-12:00
  mem: 20G
  job-name: EstimateBlocks
  output: reports/EstimateBlocks-%j.slurm.out
Fst:
  time: 0-01:00
  mem: 200M
  job-name: Fst
  output: reports/Fst-%j.slurm.out
SNPEff:
  time: 0-05:00
  mem: 30G
  job-name: SNPEff
  output: reports/SNPEff-%j.slurm.out
AlleleAtlas:
  mem: 110G
  job-name: AlleleAtlas
  output: reports/AlleleAtlas-%j.slurm.out
