ID:
  RP: RP
  NRP: NRP
Subset:
  All: AllAccessions
  Subset: EliteUSOnly
Chr: 20
ImputeRP:
  mem: 120G
  cpus: 15
ImputeNRP:
  mem: 100G
  cpus: 15
EstimateBlocks:
  mem: 10000
SNPEff:
  mem: 30G
SNPSift:
  mem: 30G
